FROM bitnami/spark:3.4.1

USER root
RUN apt update && apt upgrade
RUN apt-get install curl -y
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-azure-datalake/3.2.0/hadoop-azure-datalake-3.2.0.jar --output /opt/bitnami/spark/jars/hadoop-azure-datalake-3.2.0.jar
RUN curl https://repo1.maven.org/maven2/org/wildfly/openssl/wildfly-openssl-java/2.1.0.Final/wildfly-openssl-java-2.1.0.Final-sources.jar --output /opt/bitnami/spark/jars/wildfly-openssl-java-2.1.0.jar
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-azure/2.8.0/hadoop-azure-2.8.0.jar --output /opt/bitnami/spark/jars/hadoop-azure-2.8.0.jar
RUN curl https://repo1.maven.org/maven2/net/java/dev/jets3t/jets3t/0.9.4/jets3t-0.9.4.jar --output /opt/bitnami/spark/jars/jets3t-0.9.4.jar
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-azure/3.2.0/hadoop-azure-3.2.0.jar --output /opt/bitnami/spark/jars/hadoop-azure-3.2.0.jar
RUN curl https://repo1.maven.org/maven2/com/microsoft/azure/azure-storage/8.6.3/azure-storage-8.6.3.jar --output /opt/bitnami/spark/jars/azure-storage-8.6.3.jar
RUN curl https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar --output /opt/bitnami/spark/jars/httpclient-4.5.2.jar
RUN curl https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/9.3.24.v20180605/jetty-util-ajax-9.3.24.v20180605.jar --output /opt/bitnami/spark/jars/jetty-util-ajax-9.3.24.v20180605.jar
RUN curl https://repo1.maven.org/maven2/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar --output /opt/bitnami/spark/jars/jackson-mapper-asl-1.9.13.jar
RUN curl https://repo1.maven.org/maven2/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar --output /opt/bitnami/spark/jars/jackson-core-asl-1.9.13.jar
RUN curl https://repo1.maven.org/maven2/org/wildfly/openssl/wildfly-openssl/1.0.4.Final/wildfly-openssl-1.0.4.Final.jar --output /opt/bitnami/spark/jars/wildfly-openssl-1.0.4.Final.jar
RUN curl https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar --output /opt/bitnami/spark/jars/httpcore-4.4.4.jar
RUN curl https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar --output /opt/bitnami/spark/jars/commons-logging-1.1.3.jar
RUN curl https://repo1.maven.org/maven2/commons-codec/commons-codec/1.11/commons-codec-1.11.jar --output /opt/bitnami/spark/jars/commons-codec-1.11.jar
RUN curl https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/9.3.24.v20180605/jetty-util-9.3.24.v20180605.jar --output /opt/bitnami/spark/jars/jetty-util-9.3.24.v20180605.jar
RUN curl https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.9.4/jackson-core-2.9.4.jar --output /opt/bitnami/spark/jars/jackson-core-2.9.4.jar
RUN curl https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.jar --output /opt/bitnami/spark/jars/slf4j-api-1.7.12.jar
RUN curl https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar --output /opt/bitnami/spark/jars/commons-lang3-3.4.jar
RUN curl https://repo1.maven.org/maven2/com/microsoft/azure/azure-keyvault-core/1.0.0/azure-keyvault-core-1.0.0.jar --output /opt/bitnami/spark/jars/azure-keyvault-core-1.0.0.jar
RUN curl https://repo1.maven.org/maven2/com/google/guava/guava/20.0/guava-20.0.jar --output /opt/bitnami/spark/jars/guava-20.0.jar

COPY ./dags/spark_etl_script_docker.py /opt/bitnami/spark

COPY ./requirements_copy.txt /
RUN pip install -r /requirements_copy.txt